FROM rustembedded/cross:x86_64-unknown-linux-gnu
LABEL maintainer=soulmachine

# The openssl crate needs pkg-config and openssl
RUN yum update -y && yum install -y pkgconfig openssl-devel \
  && yum clean all && rm -rf /var/cache/yum
