FROM soulmachine/code-server:cpp-base

# Docs:
# * https://code.visualstudio.com/docs/languages/cpp
# * https://code.visualstudio.com/docs/cpp/cpp-ide

COPY --chown=$USER:$USER ./.vscode/settings-cpp.json /data/.local/share/code-server/User/settings.json

RUN wget --waitretry 15 --tries 5 --no-verbose https://github.com/microsoft/vscode-cpptools/releases/download/v1.13.8/cpptools-linux.vsix \
  && code-server --install-extension ./cpptools-linux.vsix \
  && rm ./cpptools-linux.vsix
