FROM soulmachine/code-server:cpp-base

COPY --chown=$USER:$USER ./.vscode/settings-clang.json /data/.local/share/code-server/User/settings.json

RUN code-server --install-extension llvm-vs-code-extensions.vscode-clangd
