# Forked from https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/debian/Dockerfile
FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV CONDA_HOME="/opt/conda"
ENV PATH="${CONDA_HOME}/bin:${PATH}"

ARG ANACONDA_VERSION="2025.12-2"

RUN apt-get update && apt-get upgrade -qy && apt-get dist-upgrade -qy \
 && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    wget \
 && echo "Installing Anaconda3" && \
    ARCH=$(uname -m) && \
    wget -q "https://repo.anaconda.com/archive/Anaconda3-${ANACONDA_VERSION}-Linux-${ARCH}.sh" -O ~/installer.sh && \
    /bin/bash ~/installer.sh -b -p ${CONDA_HOME} && \
    rm ~/installer.sh && \
    ln -s ${CONDA_HOME}/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". ${CONDA_HOME}/etc/profile.d/conda.sh" >> /etc/profile && \
    echo "conda activate base" >> /etc/profile && \
    echo "Accepting Anaconda Terms of Service" && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    echo "Set conda-forge as primary channel to reduce conflicts." && \
    conda config --add channels conda-forge && \
    conda update -y --all \
 && echo "Installing JupyterLab and necessary plugins" && \
    conda install -y -c conda-forge \
    ipywidgets \
    jupyterlab \
    nbconvert \
    nb_conda_kernels \
    jupyterlab-git \
    jupyter_http_over_ws \
    plotly \
    nbdime && \
    jupyter server extension enable nbdime --py --sys-prefix && \
    jupyter server extension enable jupyter_http_over_ws --sys-prefix && \
    jupyter server extension enable jupyterlab_git --sys-prefix && \
    jupyter labextension list && \
    nbdime config-git --enable --global \
 && echo "Installing necessary python libraries" && \
    conda install -y -c conda-forge \
    dask \
    matplotlib \
    numpy \
    pandas \
    pyarrow \
    pytables \
    scikit-learn \
    scipy \
    seaborn \
    statsmodels \
    tqdm \
 && conda update -y --all && conda clean -afy && \
    apt-get autoremove && apt-get autoclean && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

# Configure JupyterLab
COPY .jupyter/ /root/.jupyter

RUN mkdir /notebooks
WORKDIR /notebooks
VOLUME [ "/notebooks" ]

EXPOSE 8080

CMD [ "conda", "run", "--no-capture-output", "-n", "base", "jupyter-lab", "--ip=0.0.0.0", "--allow-root" ]
