FROM quay.io/pypa/manylinux2014_x86_64
LABEL maintainer=soulmachine

# References:
# https://github.com/pypa/python-manylinux-demo

# The openssl crate needs pkg-config and openssl
RUN yum update -y && yum install -y pkgconfig openssl-devel curl \
  && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
  && yum clean all && rm -rf /var/cache/yum

ENV PLAT=manylinux2014_x86_64

WORKDIR /project
VOLUME /project
